/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 email.gltf --transform
Author: PhantomXD (https://sketchfab.com/PhantomXD)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-gmail-logo-f8c066b10d1a475abbd69ebbe9de2b83
Title: Old Gmail Logo
*/


import { useGLTF } from '@react-three/drei'


export default function Model(props) {
  const { nodes, materials } = useGLTF('/email-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane_0.geometry} material={materials['Material.001']} position={[0, -0.07, 0]} scale={[1.225, 1.054, 1.225]}  >
      <meshStandardMaterial
        color="#1e9db3"
        
        />
      </mesh>
      <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.002']} position={[0, -0.07, 0]} scale={[1.225, 1.054, 1.225]} >
        <meshStandardMaterial
        color="purple"
        
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/email-transformed.glb')
